os: linux
dist: xenial
branches:
  only:
    - master
language: python
python:
  - "3.7"
  - "3.8"
language: bash
script:
    - chmod u+x bash run.sh && ./run.sh
notifications:
  email:
    on_success: change
    on_failure: always
